#!/bin/sh

CONFIG_PATH=/etc/letsencrypt-inwx.json

if [ -f ~/.config/letsencrypt-inwx.json ]; then
    CONFIG_PATH=~/.config/letsencrypt-inwx.json
fi

/usr/bin/letsencrypt-inwx create -c $CONFIG_PATH -d "_acme-challenge.$CERTBOT_DOMAIN" -v "$CERTBOT_VALIDATION"
